In [83]:
import pandas as pd
import numpy as np
import chardet
import re

In [2]:
file_path = "98-401-X2021003_English_CSV_data.csv"


# Read the CSV file with 'utf-8' encoding and handle errors with 'latin-1'
try:
    df = pd.read_csv(file_path, encoding='utf-8')
except UnicodeDecodeError:
    df = pd.read_csv(file_path, encoding='latin-1')

In [3]:
columns_to_keep = ['ALT_GEO_CODE','GEO_NAME', 'CHARACTERISTIC_NAME','C1_COUNT_TOTAL', 'C2_COUNT_MEN+', 'C3_COUNT_WOMEN+']

In [4]:
df =df[columns_to_keep]

In [3]:
df.sample(20)

,CENSUS_YEAR,DGUID,ALT_GEO_CODE,GEO_LEVEL,GEO_NAME,TNR_SF,TNR_LF,DATA_QUALITY_FLAG,CHARACTERISTIC_ID,CHARACTERISTIC_NAME,...,C2_COUNT_MEN+,SYMBOL.1,C3_COUNT_WOMEN+,SYMBOL.2,C10_RATE_TOTAL,SYMBOL.3,C11_RATE_MEN+,SYMBOL.4,C12_RATE_WOMEN+,SYMBOL.5
2857422,2021,2021A00054702044,4702044,Census subdivision,"Weyburn No. 67, Rural municipality (RM)",3.1,5.2,0,157,With total income,...,415.0,NaN,400.0,NaN,95.9,NaN,96.5,NaN,97.6,NaN
2867077,2021,2021A00056001010,6001010,Census subdivision,"Lake Laberge 1, Self-government (SG)",0.0,30.0,9999,1919,Ugandan,...,NaN,x,NaN,x,NaN,x,NaN,x,NaN,x
1085894,2021,2021A00052408023,2408023,Census subdivision,"Sainte-Félicité, Municipalité (MÉ)",1.8,1.0,0,1923,Central African,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
635817,2021,2021A00051313027,1313027,Census subdivision,"Edmundston, City (C)",1.6,2.2,0,1747,Belgian,...,15.0,NaN,0.0,NaN,0.1,NaN,0.2,NaN,0.0,NaN
2383524,2021,2021A00051001542,1001542,Census subdivision,"Mount Pearl, City (CY)",2.1,2.9,0,2470,Pennsylvania German,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
1708003,2021,2021A00055923037,5923037,Census subdivision,"Alberni-Clayoquot E, Regional district elector...",1.4,3.2,0,485,Kwak'wala (Kwakiutl),...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
2501256,2021,2021A00053558016,3558016,Census subdivision,"O'Connor, Township (TP)",1.5,0.0,0,1807,Peruvian,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
1405240,2021,2021A00052473010,2473010,Census subdivision,"Sainte-Thérèse, Ville (V)",2.1,2.8,0,287,"$25,000 to $29,999",...,NaN,...,NaN,...,5.6,NaN,NaN,...,NaN,...
2792249,2021,2021A00055917044,5917044,Census subdivision,"Langford, City (CY)",2.9,4.2,0,759,Ojibway-Potawatomi languages,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
981266,2021,2021S0504936,936,Census agglomeration,Ladysmith,2.5,3.5,0,2535,Nilo-Saharan languages,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
2498798,2021,2021A00053558001,3558001,Census subdivision,"Neebing, Municipality (MU)",9.7,13.4,10,1980,Intraprovincial migrants,...,35.0,NaN,55.0,NaN,3.8,NaN,2.9,NaN,5.3,NaN
1573054,2021,2021A00052482020,2482020,Census subdivision,"Cantley, Municipalité (MÉ)",2.1,3.2,0,2348,Haida,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
722005,2021,2021A00051310002,1310002,Census subdivision,"New Maryland, Village (VL)",1.4,1.0,0,1112,Dakelh (Carrier),...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
2202763,2021,2021A00054711063,4711063,Census subdivision,"Dundurn, Town (T)",1.6,1.9,0,617,Nepali,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
397531,2021,2021A00051005025,1005025,Census subdivision,"Meadows, Town (T)",1.1,4.3,0,251,Total - Income statistics for private househol...,...,NaN,...,NaN,...,NaN,...,NaN,...,NaN,...
1516366,2021,2021S0504575,575,Census agglomeration,North Bay,2.4,4.1,0,911,Polish,...,15.0,NaN,15.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
193014,2021,2021S0504330,330,Census agglomeration,Campbellton,2.0,4.1,20000,952,Bengali,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
1134686,2021,2021A00051309023,1309023,Census subdivision,"Red Bank 4, Indian reserve (IRI)",10.1,10.1,1010,726,French,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
1121085,2021,2021A00051309004,1309004,Census subdivision,"Glenelg, Parish (P)",2.6,4.1,0,280,"$200,000 and over",...,NaN,...,NaN,...,1.5,NaN,NaN,...,NaN,...
56378,2021,2021A00052496025,2496025,Census subdivision,"Pointe-Lebel, Village (VL)",2.1,5.1,0,1128,Northern Tutchone,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN

In [4]:
df['Level'] = (df['CHARACTERISTIC_NAME'].apply(len)-df['CHARACTERISTIC_NAME'].str.strip().apply(len))/2

In [5]:
max_level = int(df['Level'].max())

In [6]:
level_val=df['Level'].unique()

In [7]:
level_list =[]

In [8]:
level_list = ["Lvl-" + str(i) for i in range(0, max_level + 1)]

In [9]:
level_list

['Lvl-0',
 'Lvl-1',
 'Lvl-2',
 'Lvl-3',
 'Lvl-4',
 'Lvl-5',
 'Lvl-6',
 'Lvl-7',
 'Lvl-8']

In [10]:
for column_name in level_list:
        df[column_name] = column_name

In [11]:
for column_name in level_list:
        df[column_name] = np.nan

In [12]:
df

,CENSUS_YEAR,DGUID,ALT_GEO_CODE,GEO_LEVEL,GEO_NAME,TNR_SF,TNR_LF,DATA_QUALITY_FLAG,CHARACTERISTIC_ID,CHARACTERISTIC_NAME,...,Level,Lvl-0,Lvl-1,Lvl-2,Lvl-3,Lvl-4,Lvl-5,Lvl-6,Lvl-7,Lvl-8
0,2021,2021S0503932,932,Census metropolitan area,Abbotsford - Mission,2.7,3.7,0,1,"Population, 2021",...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,2021S0503932,932,Census metropolitan area,Abbotsford - Mission,2.7,3.7,0,2,"Population, 2016",...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,2021S0503932,932,Census metropolitan area,Abbotsford - Mission,2.7,3.7,0,3,"Population percentage change, 2016 to 2021",...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,2021S0503932,932,Census metropolitan area,Abbotsford - Mission,2.7,3.7,0,4,Total private dwellings,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,2021S0503932,932,Census metropolitan area,Abbotsford - Mission,2.7,3.7,0,5,Private dwellings occupied by usual residents,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3049324,2021,2021A00054709012,4709012,Census subdivision,"Yorkton, City (CY)",2.0,2.7,0,2627,Total - Eligibility and instruction in the min...,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3049325,2021,2021A00054709012,4709012,Census subdivision,"Yorkton, City (CY)",2.0,2.7,0,2628,Children eligible for instruction in the min...,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3049326,2021,2021A00054709012,4709012,Census subdivision,"Yorkton, City (CY)",2.0,2.7,0,2629,Eligible children who have been instructed...,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3049327,2021,2021A00054709012,4709012,Census subdivision,"Yorkton, City (CY)",2.0,2.7,0,2630,Eligible children who have not been instru...,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3049328,2021,2021A00054709012,4709012,Census subdivision,"Yorkton, City (CY)",2.0,2.7,0,2631,Children not eligible for instruction in the...,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df_play = df.copy()

In [14]:
# Iterate through the DataFrame rows
for index, row in df_play.iterrows():

    for level_column in level_list:
            if row['Level'] == int(level_column.split('-')[1]):
                characteristic_name = row['CHARACTERISTIC_NAME'].strip()
                df_play.at[index, level_column] = characteristic_name

In [15]:
# iterate each level column and update the NaN ones based on the hierarchy
level_val=df['Level'].unique()
for i in level_val:
    i = int(i)
    last_characteristic_name = ''
    # Iterate through the DataFrame rows
    for index, row in df_play.iterrows():
        if pd.notna(row[level_list[i]]):
            last_characteristic_name = row['CHARACTERISTIC_NAME'].strip()
        elif row['Level'] >= i:
            # Update the 'Lvl-x' column with the last_characteristic_name until the next 0 occurs
            df_play.at[index, level_list[i]] = last_characteristic_name

In [16]:
df_play.to_csv("Output/census_data_with_levels.csv", index=False)

## Seperator

In [17]:
#add the location of the file
df_census = pd.read_csv("Output/census_data_with_levels.csv", sep=',') 
df_census.head(10)

,CENSUS_YEAR,DGUID,ALT_GEO_CODE,GEO_LEVEL,GEO_NAME,TNR_SF,TNR_LF,DATA_QUALITY_FLAG,CHARACTERISTIC_ID,CHARACTERISTIC_NAME,...,Level,Lvl-0,Lvl-1,Lvl-2,Lvl-3,Lvl-4,Lvl-5,Lvl-6,Lvl-7,Lvl-8
0,2021,2021S0503932,932,Census metropolitan area,Abbotsford - Mission,2.7,3.7,0,1,"Population, 2021",...,0.0,"Population, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,2021S0503932,932,Census metropolitan area,Abbotsford - Mission,2.7,3.7,0,2,"Population, 2016",...,0.0,"Population, 2016",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,2021S0503932,932,Census metropolitan area,Abbotsford - Mission,2.7,3.7,0,3,"Population percentage change, 2016 to 2021",...,0.0,"Population percentage change, 2016 to 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,2021S0503932,932,Census metropolitan area,Abbotsford - Mission,2.7,3.7,0,4,Total private dwellings,...,0.0,Total private dwellings,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,2021S0503932,932,Census metropolitan area,Abbotsford - Mission,2.7,3.7,0,5,Private dwellings occupied by usual residents,...,0.0,Private dwellings occupied by usual residents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2021,2021S0503932,932,Census metropolitan area,Abbotsford - Mission,2.7,3.7,0,6,Population density per square kilometre,...,0.0,Population density per square kilometre,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2021,2021S0503932,932,Census metropolitan area,Abbotsford - Mission,2.7,3.7,0,7,Land area in square kilometres,...,0.0,Land area in square kilometres,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2021,2021S0503932,932,Census metropolitan area,Abbotsford - Mission,2.7,3.7,0,8,Total - Age groups of the population - 100% data,...,0.0,Total - Age groups of the population - 100% data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2021,2021S0503932,932,Census metropolitan area,Abbotsford - Mission,2.7,3.7,0,9,0 to 14 years,...,1.0,Total - Age groups of the population - 100% data,0 to 14 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2021,2021S0503932,932,Census metropolitan area,Abbotsford - Mission,2.7,3.7,0,10,0 to 4 years,...,2.0,Total - Age groups of the population - 100% data,0 to 14 years,0 to 4 years,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df_census['Lvl-0'].unique()

array(['Population, 2021', 'Population, 2016',
       'Population percentage change, 2016 to 2021',
       'Total private dwellings',
       'Private dwellings occupied by usual residents',
       'Population density per square kilometre',
       'Land area in square kilometres',
       'Total - Age groups of the population - 100% data',
       'Total - Distribution (%) of the population by broad age groups - 100% data',
       'Average age of the population', 'Median age of the population',
       'Total - Occupied private dwellings by structural type of dwelling - 100% data',
       'Total - Private households by household size - 100% data',
       'Number of persons in private households',
       'Average household size',
       'Total - Marital status for the total population aged 15 years and over - 100% data',
       'Total - Census families in private households by family size - 100% data',
       'Average size of census families',
       'Average number of children in census families with children',
       'Total number of census families in private households - 100% data',
       'Total - Persons in private households - 100% data',
       'Total - Household type - 100% data',
       'Total - Income statistics in 2020 for the population aged 15 years and over in private households - 100% data',
       'Total - Income statistics in 2020 for the population aged 15 years and over in private households - 25% sample data',
       'Total - Employment income statistics in 2020 for the population aged 15 years and over in private households - 25% sample data',
       'Composition of total income in 2020 of the population aged 15 years and over in private households (%) - 25% sample data',
       'Total - Total income groups in 2020 for the population aged 15 years and over in private households - 100% data',
       'Total - After-tax income groups in 2020 for the population aged 15 years and over in private households - 100% data',
       'Total - Employment income groups in 2020 for the population aged 15 years and over in private households - 100% data',
       'Total - Income statistics in 2019 for the population aged 15 years and over in private households - 100% data',
       'Total - Income statistics in 2019 for the population aged 15 years and over in private households - 25% sample data',
       'Total - Employment income statistics in 2019 for the population aged 15 years and over in private households - 25% sample data',
       'Composition of total income in 2019 of the population aged 15 years and over in private households (%) - 25% sample data',
       'Total - Income statistics for private households - 100% data',
       'Total - Income statistics for private households - 25% sample data',
       'Total - Household total income groups in 2020 for private households - 100% data',
       'Total - Household after-tax income groups in 2020 for private households - 100% data',
       'Total - Income statistics for economic families in private households - 100% data',
       'Total - Income statistics for couple-only economic families in private households - 100% data',
       'Total - Income statistics for couple-with-children economic families in private households - 100% data',
       'Total - Income statistics for one-parent economic families in private households - 100% data',
       'Total - Income statistics for persons aged 15 years and over not in economic families in private households - 100% data',
       'Total - Income statistics for economic families in private households - 25% sample data',
       'Total - Income statistics for couple-only economic families in private households - 25% sample data',
       'Total - Income statistics for couple-with-children economic families in private households - 25% sample data',
       'Total - Income statistics for one-parent economic families in private households - 25% sample data',
       'Total - Income statistics for persons aged 15 years and over not in economic families in private households - 25% sample data',
       'Total - LIM low-income status in 2020 for the population in private households - 100% data',
       'In low income based on the Low-income measure, after tax (LIM-AT)',
       'Prevalence of low income based on the Low-income measure, after tax (LIM-AT) (%)',
       'Total - LICO low-income status in 2020 for the population in private households to whom the low-income concept is applicable - 100% data',
       'In low income based on the Low-income cut-offs, after tax (LICO-AT)',
       'Prevalence of low income based on the Low-income cut-offs, after tax (LICO-AT) (%)',
       'Total - Adjusted after-tax economic family income decile group for the population in private households - 100% data',
       'Total - Inequality measures for the population in private households - 100% data',
       'Total - Knowledge of official languages for the total population excluding institutional residents - 100% data',
       'Total - First official language spoken for the total population excluding institutional residents - 100% data',
       'Total - Mother tongue for the total population excluding institutional residents - 100% data',
       'Total - All languages spoken at home for the total population excluding institutional residents - 100% data',
       'Total - Language spoken most often at home for the total population excluding institutional residents - 100% data',
       'Total - Other language(s) spoken regularly at home for the total population excluding institutional residents - 100% data',
       'Total - Knowledge of languages for the population in private households - 25% sample data',
       'Total - Indigenous identity for the population in private households - 25% sample data',
       'Total - Registered or Treaty Indian status for the population in private households - 25% sample data',
       'Total - Private households by tenure - 25% sample data',
       'Total - Occupied private dwellings by condominium status - 25% sample data',
       'Total - Occupied private dwellings by number of bedrooms - 25% sample data',
       'Total - Occupied private dwellings by number of rooms - 25% sample data',
       'Average number of rooms per dwelling',
       'Total - Private households by number of persons per room - 25% sample data',
       'Total - Private households by housing suitability - 25% sample data',
       'Total - Occupied private dwellings by period of construction - 25% sample data',
       'Total - Occupied private dwellings by dwelling condition - 25% sample data',
       'Total - Private households by number of household maintainers - 25% sample data',
       'Total - Private households by age of primary household maintainers - 25% sample data',
       'Total - Owner and tenant households with household total income greater than zero, in non-farm, non-reserve private dwellings by shelter-cost-to-income ratio - 25% sample data',
       'Total - Occupied private dwellings by housing indicators - 25% sample data',
       'Total - Owner and tenant households with household total income greater than zero and shelter-cost-to-income ratio less than 100%, in non-farm, non-reserve private dwellings - 25% sample data',
       'Total - Owner households in non-farm, non-reserve private dwellings - 25% sample data',
       'Total - Tenant households in non-farm, non-reserve private dwellings - 25% sample data',
       'Total - Households living in a dwelling provided by the local government, First Nation or Indian band in non-farm private dwellings - 25% sample data',
       'Total - Indigenous ancestry for the population in private households - 25% sample data',
       'Total - Citizenship for the population in private households - 25% sample data',
       'Total - Immigrant status and period of immigration for the population in private households - 25% sample data',
       'Total - Age at immigration for the immigrant population in private households - 25% sample data',
       'Total - Place of birth for the immigrant population in private households - 25% sample data',
       'Total - Place of birth for the recent immigrant population in private households - 25% sample data',
       'Total - Generation status for the population in private households - 25% sample data',
       'Total - Admission category and applicant type for the immigrant population in private households who were admitted between 1980 and 2021 - 25% sample data',
       'Total - Pre-admission experience for the immigrant population in private households who were admitted between 1980 and 2021 - 25% sample data',
       'Total - Visible minority for the population in private households - 25% sample data',
       'Total - Ethnic or cultural origin for the population in private households - 25% sample data',
       'Total - Religion for the population in private households - 25% sample data',
       'Total - Mobility status 1 year ago - 25% sample data',
       'Total - Mobility status 5 years ago - 25% sample data',
       'Total - Secondary (high) school diploma or equivalency certificate for the population aged 15 years and over in private households - 25% sample data',
       'Total - Secondary (high) school diploma or equivalency certificate for the population aged 25 to 64 years in private households - 25% sample data',
       'Total - Highest certificate, diploma or degree for the population aged 15 years and over in private households - 25% sample data',
       'Total - Highest certificate, diploma or degree for the population aged 25 to 64 years in private households - 25% sample data',
       'Total - Major field of study - Classification of Instructional Programs (CIP) 2021 for the population aged 15 years and over in private households - 25% sample data',
       'Total - Major field of study - Classification of Instructional Programs (CIP) 2021 for the population aged 25 to 64 years in private households - 25% sample data',
       'Total - Location of study compared with province or territory of residence for the population aged 25 to 64 years in private households - 25% sample data',
       'Total - Population aged 15 years and over by labour force status - 25% sample data',
       'Participation rate', 'Employment rate', 'Unemployment rate',
       'Total - Population aged 15 years and over by work activity during the reference year - 25% sample data',
       'Total - Labour force aged 15 years and over by class of worker including job permanency - 25% sample data',
       'Total - Labour force aged 15 years and over by occupation - Broad category - National Occupational Classification (NOC) 2021 - 25% sample data',
       'Total - Labour force aged 15 years and over by industry - Sectors - North American Industry Classification System (NAICS) 2017 - 25% sample data',
       'Total - All languages used at work for the population in private households aged 15 years and over who worked since January 1, 2020 - 25% sample data',
       'Total - Language used most often at work for the population aged 15 years and over who worked since January 1, 2020, in private households, 2021 Census - 25% sample data',
       'Total - Other language(s) used regularly at work for the population in private households aged 15 years and over who worked since January 1, 2020 - 25% sample data',
       'Total - Place of work status for the employed labour force aged 15 years and over - 25% sample data',
       'Total - Commuting destination for the employed labour force aged 15 years and over with a usual place of work - 25% sample data',
       'Total - Main mode of commuting for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data',
       'Total - Commuting duration for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data',
       'Total - Time leaving for work for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data',
       'Total - Eligibility for instruction in the minority official language for the population in private households born in 2003 or later - 100% data',
       'Total - Eligibility and instruction in the minority official language, for the population in private households born between 2003 and 2015 (inclusive) - 100% data'],
      dtype=object)

Visual Minority

In [143]:
def create_pivot_table(df, filter_condition):
    # Filter the DataFrame based on the condition
    filtered_df = df[df['Lvl-0'] == filter_condition]

    # Create the pivot table
    pivot_table = filtered_df.pivot_table(
        index=['ALT_GEO_CODE', 'GEO_NAME'],
        columns='Lvl-1',
        values=['C1_COUNT_TOTAL', 'C2_COUNT_MEN+', 'C3_COUNT_WOMEN+']
    )

    return pivot_table

# usage:
pivot_vis_minority = create_pivot_table(df_census, 'Total - Visible minority for the population in private households - 25% sample data')
pivot_vis_minority

                                                                 C1_COUNT_TOTAL  \
Lvl-1                                                    Not a visible minority
ALT_GEO_CODE GEO_NAME
1            St. John's                                                196270.0
10           Grand Falls-Windsor                                        13220.0
11           Gander                                                     12760.0
15           Corner Brook                                               28335.0
105          Charlottetown                                              66325.0
...                                                                         ...
6001055      Ibex Valley, Hamlet (HAM)                                    650.0
6001058      Marsh Lake, Unorganized (NO)                                 735.0
6001059      Macpherson-Grizzly Valley, Unorganized (NO)                 1480.0
6001060      Whitehorse, Unorganized, Unorganized (NO)                    300.0
6106023      Yellowknife, City (CY)                                     15920.0

                                                                                            \
Lvl-1                                                    Total visible minority population
ALT_GEO_CODE GEO_NAME
1            St. John's                                                        1930.769231
10           Grand Falls-Windsor                                                 58.076923
11           Gander                                                              48.846154
15           Corner Brook                                                        96.538462
105          Charlottetown                                                     1701.923077
...                                                                                    ...
6001055      Ibex Valley, Hamlet (HAM)                                            0.000000
6001058      Marsh Lake, Unorganized (NO)                                         0.000000
6001059      Macpherson-Grizzly Valley, Unorganized (NO)                          6.153846
6001060      Whitehorse, Unorganized, Unorganized (NO)                            0.000000
6106023      Yellowknife, City (CY)                                             613.076923

                                                                  C2_COUNT_MEN+  \
Lvl-1                                                    Not a visible minority
ALT_GEO_CODE GEO_NAME
1            St. John's                                                 94950.0
10           Grand Falls-Windsor                                         6355.0
11           Gander                                                      6245.0
15           Corner Brook                                               13695.0
105          Charlottetown                                              31810.0
...                                                                         ...
6001055      Ibex Valley, Hamlet (HAM)                                    345.0
6001058      Marsh Lake, Unorganized (NO)                                 405.0
6001059      Macpherson-Grizzly Valley, Unorganized (NO)                  745.0
6001060      Whitehorse, Unorganized, Unorganized (NO)                    160.0
6106023      Yellowknife, City (CY)                                      7945.0

                                                                                            \
Lvl-1                                                    Total visible minority population
ALT_GEO_CODE GEO_NAME
1            St. John's                                                        1018.461538
10           Grand Falls-Windsor                                                 28.076923
11           Gander                                                              26.923077
15           Corner Brook                                                        56.538462
105          Charlottetown                                                      905.000000
...                                                                                    ...
6001055      Ibex Valley, Hamlet (HAM)                                            0.000000
6001058      Marsh Lake, Unorganized (NO)                                         0.000000
6001059      Macpherson-Grizzly Valley, Unorganized (NO)                          2.307692
6001060      Whitehorse, Unorganized, Unorganized (NO)                            0.000000
6106023      Yellowknife, City (CY)                                             298.461538

                                                                C3_COUNT_WOMEN+  \
Lvl-1                                                    Not a visible minority
ALT_GEO_CODE GEO_NAME
1            St. John's                                                101320.0
10           Grand Falls-Windsor                                         6865.0
11           Gander                                                      6515.0
15           Corner Brook                                               14645.0
105          Charlottetown                                              34510.0
...                                                                         ...
6001055      Ibex Valley, Hamlet (HAM)                                    305.0
6001058      Marsh Lake, Unorganized (NO)                                 325.0
6001059      Macpherson-Grizzly Valley, Unorganized (NO)                  730.0
6001060      Whitehorse, Unorganized, Unorganized (NO)                    140.0
6106023      Yellowknife, City (CY)                                      7970.0


Lvl-1                                                    Total visible minority population
ALT_GEO_CODE GEO_NAME
1            St. John's                                                         911.153846
10           Grand Falls-Windsor                                                 28.076923
11           Gander                                                              20.769231
15           Corner Brook                                                        39.615385
105          Charlottetown                                                      795.769231
...                                                                                    ...
6001055      Ibex Valley, Hamlet (HAM)                                            0.000000
6001058      Marsh Lake, Unorganized (NO)                                         0.000000
6001059      Macpherson-Grizzly Valley, Unorganized (NO)                          3.076923
6001060      Whitehorse, Unorganized, Unorganized (NO)                            0.000000
6106023      Yellowknife, City (CY)                                             315.384615

[1089 rows x 6 columns]

In [144]:
def update_pivot_table(pivot_indigen):
    """
    Updates the column names in the pivot table by combining ALT_GEO_CODE and GEO_NAME from the index
    and extracting the part inside parentheses for each column.

    Parameters:
    pivot_indigen (DataFrame): The DataFrame with a MultiIndex for rows and requires column name updates.

    Returns:
    DataFrame: The DataFrame with updated column names.
    """
    # Extract ALT_GEO_CODE and GEO_NAME from the multi-index
    pivot_indigen.columns = [
        f'{geo_code}_{geo_name}_{col}' 
        for geo_code, geo_name, col in zip(
            pivot_indigen.index.get_level_values(0), 
            pivot_indigen.index.get_level_values(1), 
            pivot_indigen.columns
        )
    ]

    # Update column names to extract content inside parentheses for each column
    pivot_indigen.columns = [
        re.search(r'\((.*?)\)', col).group(1) if re.search(r'\((.*?)\)', col) else col
        for col in pivot_indigen.columns
    ]
    
    return pivot_indigen



pivot_vis_minority = update_pivot_columns(pivot_vis_minority)
column_sums = pivot_vis_minority.sum().round(0)
column_sums

'C1_COUNT_TOTAL', 'Not a visible minority'                42120820.0
'C1_COUNT_TOTAL', 'Total visible minority population'      2909457.0
'C2_COUNT_MEN+', 'Not a visible minority'                 20767075.0
'C2_COUNT_MEN+', 'Total visible minority population'       1421923.0
'C3_COUNT_WOMEN+', 'Not a visible minority'               21353645.0
'C3_COUNT_WOMEN+', 'Total visible minority population'     1487257.0
dtype: float64

In [145]:
pivot_indigen = create_pivot_table(df_census, 'Total - Indigenous ancestry for the population in private households - 25% sample data')
# Update column names to extract content inside parentheses for each tuple

pivot_indigen = update_pivot_columns(pivot_indigen)
column_sums = pivot_indigen.sum().round(0)
column_sums

'C1_COUNT_TOTAL', 'Indigenous ancestry (only                       292324.0
'C1_COUNT_TOTAL', 'Indigenous and non-Indigenous ancestries'       545827.0
'C1_COUNT_TOTAL', 'Non-Indigenous ancestry only'                 58239555.0
'C2_COUNT_MEN+', 'Indigenous ancestry (only                        138894.0
'C2_COUNT_MEN+', 'Indigenous and non-Indigenous ancestries'        260274.0
'C2_COUNT_MEN+', 'Non-Indigenous ancestry only'                  28679940.0
'C3_COUNT_WOMEN+', 'Indigenous ancestry (only                      153163.0
'C3_COUNT_WOMEN+', 'Indigenous and non-Indigenous ancestries'      285342.0
'C3_COUNT_WOMEN+', 'Non-Indigenous ancestry only'                29559615.0
dtype: float64

In [146]:
pivot_citiz = create_pivot_table(df_census, 'Total - Citizenship for the population in private households - 25% sample data')
pivot_citiz = update_pivot_columns(pivot_citiz)
column_sums = pivot_citiz.sum().round(0)
column_sums

'C1_COUNT_TOTAL', 'Canadian citizens'         36573558.0
'C1_COUNT_TOTAL', 'Not Canadian citizens'      6119735.0
'C2_COUNT_MEN+', 'Canadian citizens'          17972205.0
'C2_COUNT_MEN+', 'Not Canadian citizens'       3026270.0
'C3_COUNT_WOMEN+', 'Canadian citizens'        18601203.0
'C3_COUNT_WOMEN+', 'Not Canadian citizens'     3092930.0
dtype: float64

In [147]:
pivot_immmig = create_pivot_table(df_census, 'Total - Immigrant status and period of immigration for the population in private households - 25% sample data')
pivot_immmig = update_pivot_columns(pivot_immmig)
column_sums =pivot_immmig.sum().round(0)
column_sums

'C1_COUNT_TOTAL', 'Immigrants'                   4608544.0
'C1_COUNT_TOTAL', 'Non-immigrants'              43129965.0
'C1_COUNT_TOTAL', 'Non-permanent residents'      1789965.0
'C2_COUNT_MEN+', 'Immigrants'                    2193174.0
'C2_COUNT_MEN+', 'Non-immigrants'               21391670.0
'C2_COUNT_MEN+', 'Non-permanent residents'        962490.0
'C3_COUNT_WOMEN+', 'Immigrants'                  2415027.0
'C3_COUNT_WOMEN+', 'Non-immigrants'             21738515.0
'C3_COUNT_WOMEN+', 'Non-permanent residents'      827015.0
dtype: float64

In [148]:
pivot_immmigage = create_pivot_table(df_census, 'Total - Age at immigration for the immigrant population in private households - 25% sample data')
pivot_immmigage = update_pivot_columns(pivot_immmigage)
column_sums =pivot_immmigage.sum().round(0)
column_sums

'C1_COUNT_TOTAL', '15 to 24 years'        3057800.0
'C1_COUNT_TOTAL', '25 to 44 years'        7310620.0
'C1_COUNT_TOTAL', '45 years and over'     1545595.0
'C1_COUNT_TOTAL', '5 to 14 years'         2737080.0
'C1_COUNT_TOTAL', 'Under 5 years'         1409505.0
'C2_COUNT_MEN+', '15 to 24 years'         1379885.0
'C2_COUNT_MEN+', '25 to 44 years'         3444450.0
'C2_COUNT_MEN+', '45 years and over'       704375.0
'C2_COUNT_MEN+', '5 to 14 years'          1389020.0
'C2_COUNT_MEN+', 'Under 5 years'           711965.0
'C3_COUNT_WOMEN+', '15 to 24 years'       1677585.0
'C3_COUNT_WOMEN+', '25 to 44 years'       3865890.0
'C3_COUNT_WOMEN+', '45 years and over'     840975.0
'C3_COUNT_WOMEN+', '5 to 14 years'        1347665.0
'C3_COUNT_WOMEN+', 'Under 5 years'         697045.0
dtype: float64

In [149]:
pivot_immmigplaceofbirth = create_pivot_table(df_census, 'Total - Place of birth for the immigrant population in private households - 25% sample data')
pivot_immmigplaceofbirth= update_pivot_columns(pivot_immmigplaceofbirth)
column_sums =pivot_immmigplaceofbirth.sum().round(0)
column_sums

'C1_COUNT_TOTAL', 'Africa'                                292602.0
'C1_COUNT_TOTAL', 'Americas'                              375294.0
'C1_COUNT_TOTAL', 'Asia'                                  941039.0
'C1_COUNT_TOTAL', 'Europe'                                423469.0
'C1_COUNT_TOTAL', 'Oceania and other places of birth'     112010.0
'C2_COUNT_MEN+', 'Africa'                                 146456.0
'C2_COUNT_MEN+', 'Americas'                               170400.0
'C2_COUNT_MEN+', 'Asia'                                   443835.0
'C2_COUNT_MEN+', 'Europe'                                 204520.0
'C2_COUNT_MEN+', 'Oceania and other places of birth'       55735.0
'C3_COUNT_WOMEN+', 'Africa'                               145918.0
'C3_COUNT_WOMEN+', 'Americas'                             204509.0
'C3_COUNT_WOMEN+', 'Asia'                                 496969.0
'C3_COUNT_WOMEN+', 'Europe'                               218534.0
'C3_COUNT_WOMEN+', 'Oceania and other places of birth'     56035.0
dtype: float64

In [150]:
pivot_immmigethnic = create_pivot_table(df_census, 'Total - Ethnic or cultural origin for the population in private households - 25% sample data')
pivot_immmigethnic= update_pivot_columns(pivot_immmigethnic)
column_sums =pivot_immmigethnic.sum().round(0)
column_sums

'C1_COUNT_TOTAL', 'Abenaki'              25025.0
'C1_COUNT_TOTAL', 'Acadian'             395895.0
'C1_COUNT_TOTAL', 'Afghan'              191605.0
'C1_COUNT_TOTAL', 'African American'     56315.0
'C1_COUNT_TOTAL', 'African Canadian'     65085.0
                                          ...
T                                         1520.0
RM                                        7930.0
CY                                       39585.0
T                                        27605.0
RM                                        8695.0
Length: 750, dtype: float64

In [151]:
# Assuming these are your DataFrames
dataframes = [
    pivot_vis_minority,
    pivot_indigen,
    pivot_citiz,
    pivot_immmig,
    pivot_immmigage,
    pivot_immmigplaceofbirth
]

# Merge DataFrames iteratively
merged_df = dataframes[0]
for df in dataframes[1:]:
    merged_df = merged_df.merge(df, on=["ALT_GEO_CODE","GEO_NAME"], how="outer")  # Using outer join for completeness

merged_df

,,"'C1_COUNT_TOTAL', 'Not a visible minority'","'C1_COUNT_TOTAL', 'Total visible minority population'","'C2_COUNT_MEN+', 'Not a visible minority'","'C2_COUNT_MEN+', 'Total visible minority population'","'C3_COUNT_WOMEN+', 'Not a visible minority'","'C3_COUNT_WOMEN+', 'Total visible minority population'","'C1_COUNT_TOTAL', 'Indigenous ancestry (only","'C1_COUNT_TOTAL', 'Indigenous and non-Indigenous ancestries'","'C1_COUNT_TOTAL', 'Non-Indigenous ancestry only'","'C2_COUNT_MEN+', 'Indigenous ancestry (only",...,"'C2_COUNT_MEN+', 'Africa'","'C2_COUNT_MEN+', 'Americas'","'C2_COUNT_MEN+', 'Asia'","'C2_COUNT_MEN+', 'Europe'","'C2_COUNT_MEN+', 'Oceania and other places of birth'","'C3_COUNT_WOMEN+', 'Africa'","'C3_COUNT_WOMEN+', 'Americas'","'C3_COUNT_WOMEN+', 'Asia'","'C3_COUNT_WOMEN+', 'Europe'","'C3_COUNT_WOMEN+', 'Oceania and other places of birth'"
ALT_GEO_CODE,GEO_NAME,,,,,,,,,,,,,,,,,,,,,
1,St. John's,196270.0,1930.769231,94950.0,1018.461538,101320.0,911.153846,1027.5,2335.0,197615.0,470.0,...,150.000000,115.833333,204.444444,176.176471,30.0,126.363636,130.833333,220.833333,128.823529,50.0
10,Grand Falls-Windsor,13220.0,58.076923,6355.0,28.076923,6865.0,28.076923,155.0,182.5,12475.0,83.0,...,0.909091,1.666667,4.444444,4.411765,0.0,0.000000,2.083333,8.611111,3.529412,0.0
11,Gander,12760.0,48.846154,6245.0,26.923077,6515.0,20.769231,216.5,216.0,11630.0,100.0,...,6.818182,2.500000,5.833333,5.000000,0.0,1.363636,2.083333,7.777778,2.647059,0.0
15,Corner Brook,28335.0,96.538462,13695.0,56.538462,14645.0,39.615385,1485.5,1240.0,19885.0,703.0,...,5.000000,7.916667,13.333333,14.705882,0.0,5.000000,6.250000,11.666667,13.529412,0.0
105,Charlottetown,66325.0,1701.923077,31810.0,905.000000,34510.0,795.769231,217.5,510.5,74955.0,110.0,...,38.181818,91.666667,273.055556,107.941176,30.0,37.727273,96.250000,268.055556,115.294118,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6001055,"Ibex Valley, Hamlet (HAM)",650.0,0.000000,345.0,0.000000,305.0,0.000000,38.5,44.0,375.0,26.0,...,0.000000,0.000000,0.000000,2.647059,0.0,0.000000,1.666667,0.000000,0.588235,0.0
6001058,"Marsh Lake, Unorganized (NO)",735.0,0.000000,405.0,0.000000,325.0,0.000000,6.0,4.5,705.0,6.0,...,0.000000,1.666667,0.000000,1.470588,0.0,0.000000,0.000000,0.000000,2.352941,0.0
6001059,"Macpherson-Grizzly Valley, Unorganized (NO)",1480.0,6.153846,745.0,2.307692,730.0,3.076923,23.0,40.0,1300.0,8.5,...,0.000000,0.000000,0.000000,7.352941,0.0,0.000000,0.000000,0.833333,11.176471,0.0
6001060,"Whitehorse, Unorganized, Unorganized (NO)",300.0,0.000000,160.0,0.000000,140.0,0.000000,0.0,5.5,275.0,0.0,...,0.000000,0.000000,0.000000,4.117647,0.0,0.000000,0.000000,0.000000,3.235294,0.0
6106023,"Yellowknife, City (CY)",15920.0,613.076923,7945.0,298.461538,7970.0,315.384615,879.0,608.0,14950.0,387.5,...,66.818182,15.833333,91.388889,34.705882,15.0,47.727273,22.083333,106.111111,27.058824,30.0

In [152]:
# Read a portion of the file to detect encoding
with open('98-401-X2021003_Geo_starting_row.CSV', 'rb') as file:
    result = chardet.detect(file.read(10000))
try:
    geo_data = pd.read_csv('98-401-X2021003_Geo_starting_row.CSV', encoding='utf-8')
except UnicodeDecodeError:
    geo_data = pd.read_csv('98-401-X2021003_Geo_starting_row.CSV', encoding='latin-1')
# Rename the index to 'GEO_NAME'
geo_data_with_index = geo_data.set_index('Geo Name')
geo_data_with_index = geo_data_with_index.rename_axis('GEO_NAME')

In [154]:
# Reset the index of merged_df to make 'GEO_NAME' a column
merged_df_reset = merged_df.reset_index()

# Ensure 'GEO_NAME' is in both DataFrames and 'GEO_NAME' is a column in geo_data_with_index
geo_data_with_index = geo_data_with_index.reset_index()

# Perform the merge on the 'GEO_NAME' column
merged_result = pd.merge(
    geo_data_with_index,
    merged_df_reset,
    on='GEO_NAME',
    how='left'  # You can also use 'inner' or 'outer' based on your need
)

# Display the merged result
merged_result.shape

(1159, 65)